# Generated by Django 6.0.4 on 2026-04-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.BigIntegerField()),
                ("chat_id", models.BigIntegerField()),
                ("chat_name", models.CharField(blank=True, max_length=255)),
                ("sender_id", models.BigIntegerField(blank=True, null=True)),
                ("sender_name", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField(blank=True)),
                ("date", models.DateTimeField()),
                ("raw", models.JSONField(default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("chat_id", "message_id")},
            },
        ),
    ]
