# Generated by Django 6.0.4 on 2026-04-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrammessage",
            name="media_downloaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="telegrammessage",
            name="media_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="telegrammessage",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("photo", "Photo"),
                    ("video", "Video"),
                    ("voice", "Voice"),
                    ("audio", "Audio"),
                    ("sticker", "Sticker"),
                    ("gif", "GIF"),
                    ("video_note", "Video Note"),
                    ("document", "Document"),
                    ("unknown", "Unknown"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
