# Generated by Django 6.0.4 on 2026-04-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0002_telegrammessage_media_downloaded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrammessage",
            name="transcription",
            field=models.TextField(blank=True),
        ),
    ]
