# Generated by Django 6.0.4 on 2026-05-15 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_activesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="aliases",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="contact",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_from",
                to="common.contact",
            ),
        ),
        migrations.AlterField(
            model_name="activesession",
            name="id",
            field=models.IntegerField(
                default=1, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="CachedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(db_index=True, max_length=128)),
                ("calendar_id", models.CharField(db_index=True, max_length=255)),
                (
                    "calendar_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                (
                    "start_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, default="", max_length=512)),
                ("description", models.TextField(blank=True, default="")),
                ("attendees", models.JSONField(default=list)),
                ("meet_link", models.URLField(blank=True, default="", max_length=512)),
                (
                    "organizer_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_todo", models.BooleanField(db_index=True, default=False)),
                ("created_by_us", models.BooleanField(default=False)),
                ("raw", models.JSONField(default=dict)),
                ("last_seen_at", models.DateTimeField(db_index=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ["-start_at"],
                "indexes": [
                    models.Index(
                        fields=["start_at", "is_todo"],
                        name="common_cach_start_a_e84cce_idx",
                    ),
                    models.Index(
                        fields=["calendar_id", "-start_at"],
                        name="common_cach_calenda_dc6bf8_idx",
                    ),
                ],
                "unique_together": {("google_id", "calendar_id")},
            },
        ),
    ]
