# Generated by Django 6.0.4 on 2026-05-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_contact_aliases_contact_merged_into_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedevent",
            name="google_id",
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
