# Generated by Django 6.0.4 on 2026-05-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=32)),
                ("model", models.CharField(db_index=True, max_length=64)),
                ("operation", models.CharField(db_index=True, max_length=32)),
                ("source", models.CharField(db_index=True, max_length=32)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("duration_ms", models.IntegerField(default=0)),
                ("ref_type", models.CharField(blank=True, default="", max_length=64)),
                ("ref_id", models.CharField(blank=True, default="", max_length=64)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "source"],
                        name="usage_usage_created_a0dcf0_idx",
                    ),
                    models.Index(
                        fields=["-created_at", "provider", "model"],
                        name="usage_usage_created_21b9a0_idx",
                    ),
                ],
            },
        ),
    ]
