# Generated by Django 6.0.4 on 2026-04-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=128)),
                ("chat_jid", models.CharField(db_index=True, max_length=128)),
                ("chat_name", models.CharField(blank=True, max_length=255)),
                ("sender_jid", models.CharField(blank=True, max_length=128)),
                ("sender_name", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField(blank=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("voice", "Voice"),
                            ("audio", "Audio"),
                            ("sticker", "Sticker"),
                            ("gif", "GIF"),
                            ("document", "Document"),
                            ("location", "Location"),
                            ("contact", "Contact"),
                            ("unknown", "Unknown"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("media_downloaded", models.BooleanField(default=False)),
                ("media_path", models.CharField(blank=True, max_length=500)),
                ("transcription", models.TextField(blank=True)),
                ("date", models.DateTimeField()),
                ("raw", models.JSONField(default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("is_from_me", models.BooleanField(default=False)),
                ("is_group", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("chat_jid", "message_id")},
            },
        ),
    ]
