# Generated by Django 6.0.4 on 2026-05-09 15:09

import sources.plaud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlaudRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plaud_id",
                    models.CharField(
                        blank=True, default="", max_length=64, unique=True
                    ),
                ),
                ("file", models.FileField(upload_to=sources.plaud.models._upload_path)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("duration_ms", models.BigIntegerField(default=0)),
                ("serial_number", models.CharField(blank=True, max_length=64)),
                ("transcription", models.TextField(blank=True)),
                ("processed", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-recorded_at", "-created_at"],
            },
        ),
    ]
