# Generated by Django 6.0.4 on 2026-05-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plaud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plaudrecording",
            name="summarized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plaudrecording",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plaudrecording",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
