# Generated by Django 6.0.4 on 2026-04-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#64748b", max_length=20)),
                ("gmail_label_id", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="GmailSyncState",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("history_id", models.CharField(blank=True, max_length=50)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gmail_id", models.CharField(max_length=100, unique=True)),
                ("thread_id", models.CharField(blank=True, max_length=100)),
                ("subject", models.CharField(blank=True, max_length=1000)),
                ("sender", models.CharField(blank=True, max_length=500)),
                ("sender_email", models.CharField(blank=True, max_length=254)),
                ("snippet", models.TextField(blank=True)),
                ("body_text", models.TextField(blank=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("gmail_labels", models.JSONField(default=list)),
                ("analyzed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="messages", to="email_source.emailtag"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
