# Generated by Django 6.0.4 on 2026-05-15 14:58

import django.db.models.deletion
import sources.rss.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0002_rsstopic_rssarticle_analyzed_rssdailysummary"),
    ]

    operations = [
        migrations.CreateModel(
            name="RssDailyAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "file",
                    models.FileField(upload_to=sources.rss.models._audio_upload_path),
                ),
                ("summary_updated_at", models.DateTimeField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audios",
                        to="rss.rsstopic",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "topic__order"],
                "unique_together": {("topic", "date")},
            },
        ),
    ]
