# Generated by Django 6.0.4 on 2026-05-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0003_rssdailyaudio"),
    ]

    operations = [
        migrations.CreateModel(
            name="RssAudioJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=16,
                    ),
                ),
                ("total_sections", models.IntegerField(default=0)),
                ("completed_sections", models.IntegerField(default=0)),
                (
                    "current_topic_slug",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
